<?php

namespace app\admin\controller;

use think\Controller;

class Article extends Controller
{
    protected $db;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }

    public function index(){
        $field = $this->db->getAll(2);
        $this->assign('field',$field);
        return $this->fetch();
    }
    public function store(){

        if (request()->isPost()){
            $res = $this->db->store(input('post.'));

            if ($res['valid']){
                $this->success($res['msg'],'index');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }


        $cateData = (new \app\common\model\Category())->getAll();
        $this->assign('cateData',$cateData);

        $tagData = db('tag')->select();
        $this->assign('tagData',$tagData);
        return $this->fetch();
    }

    public function edit(){

        if (request()->isPost()){
            $res = $this->db->edit(input('post.'));
            if ($res['valid']){
                $this->success($res['msg'],'index');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }

        $arc_id = input('param.arc_id');
        $cateData = (new \app\common\model\Category())->getAll();
        $this->assign('cateData',$cateData);

        $tagData = db('tag')->select();
        $this->assign('tagData',$tagData);

        $oldData = db('article')->find($arc_id);
        $this->assign('oldData',$oldData);
        $tag_ids = db('arc_tag')->where('arc_id',$arc_id)->column('tag_id');
        $this->assign('tag_ids',$tag_ids);

        return $this->fetch();
    }
    public function reqycle(){
        $field = $this->db->getAll(1);
        $this->assign('field',$field);
        return $this->fetch();
    }
    public function changeSort(){
        if (request()->isAjax()){
            $res = $this->db->changeSort(input('post.'));
            if ($res['valid']){
                $this->success($res['msg'],'index');exit;
            }else{
                $this->success($res['msg']);exit;
            }
        }
    }

    public function delToRecyle(){
        $arc_id = input('param.arc_id');
        if ($this->db->save(['is_recycle'=>1],['arc_id'=>$arc_id])){
            $this->success('操作成功','index');exit;
        }else{
            $this->error('操作失败','index');exit;
        }
    }

    public function recovery(){
        $arc_id = input('param.arc_id');
        if ($this->db->save(['is_recycle'=>2],['arc_id'=>$arc_id])){
            $this->success('操作成功','index');exit;
        }else{
            $this->error('操作失败','index');exit;
        }
    }

    public function del(){
        $arc_id = input('param.arc_id');
        $res = $this->db->del($arc_id);
        if ($res['valid']){
            $this->success($res['msg']);exit;
        }
        else{
            $this->error($res['msg']);exit;
        }
    }
}
