<?php

namespace app\admin\controller;

use think\Controller;

class Tag extends Controller
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Tag();
    }

    public function index()
    {
        $field = db('tag')->paginate(10);
        $this->assign('field',$field);
        return $this->fetch();
    }

    public function store()
    {
        $tag_id = input('param.tag_id');

        if (request()->isPost()){
            $res = $this->db->store(input('post.'));
            if ($res['valid']){
                $this->success($res['msg'],'index');exit;
            }else{
                $this->error($res['msg']);exit;
            }
        }
        if ($tag_id){
            $oldData = $this->db->find($tag_id);
        }else{
            $oldData = ['tag_name'=>''];
        }
        $this->assign('oldData',$oldData);
        return $this->fetch();
    }

    public function del()
    {
        $tag_id = input('get.tag_id');
        if (\app\common\model\Tag::destroy($tag_id)){
            $this->success('删除成功');
        }else{
            $this->error('删除失败');
        }
    }
}
